### ISSUE TITLE
Problema quando copia os CPF's do excel para a tabela de geração dos certificados

### ISSUE THREAD

**Issue by hugolima01** [vinigracindo/sgce#1]
Quando eu copio os CPF's de uma tabela do excel e colo na tabela do SGCE para gerar certificados o comando Control+C e Control+V adiciona um espaço em branco no final do CPF e o sistema fica dizendo que o CPF é inválido. Eu tenho que ir linha por linha removendo todos os espaços em branco.  Onde posso alterar para remover esse problema? Não é bug, mas atrapalha quando gera um monte de certificados porque tenho que ficar tirando um a um.

**Comment by vinigracindo** [comment]
Gostaria de mais detalhes. Como eu posso reproduzir o problema? Não entendi bem. Seria na hora de preencher a planilha dos certificados?

**Comment by hugolima01** [comment]
Crie um evento. Depois crie um modelo qualquer. Clique em gerar certificados. Agora faça o seguinte:
1- Digite 10 CPF's em uma tabela do excel.
2- Copie todos os 10 CPF's do excel e cole na planilha.
3- Clique em gerar certificados.

O sistema vai mostrar que os CPF's estão inválidos, mas na verdade existe um espaço em branco no final de todos os CPF's que você precisa ir linha por linha e apagar para gerar os certificados. O que preciso é que o sistema ignore os espaços em brancos nos finais na hora de validar.
