### ISSUE TITLE
Editar senha usuarios.

### ISSUE THREAD

**Issue by ronalddmarks** [vinigracindo/sgce#11]
Apos efetuar o cadastro de usuários não  consigo alterar a senha que foi criada, tem algum menu que faça essa função?

**Comment by vinigracindo** [comment]
@ronalddmarks Adicionado.

**Comment by ronalddmarks** [comment]
Obrigado @vinigracindo O sistema foi implantado o pessoal responsável pelos cursos estão fazendo bom proveito.
Obrigado pelo trabalho!
