### ISSUE TITLE
Nome do modelo de certificado com acento. 

### ISSUE THREAD

**Issue by ronalddmarks** [vinigracindo/sgce#13]
Quando e criado um modelo de certificado com acentuação não e possível visualizar o modelo dando Internal Server Erro.

![image](https://user-images.githubusercontent.com/12687649/92175908-dbf0c480-ee13-11ea-9bb0-1e4831870fad.png)

_______________________________________________________________________________________________

![image](https://user-images.githubusercontent.com/12687649/92175811-a3e98180-ee13-11ea-84c3-6c7fca6c86bb.png)

**Comment by micheldiniz** [comment]
Boa tarde, 
alterei o arquivo views.py e editei a função _template_preview_render_pdf_, onde é gerado o nome do arquivo pdf, para que seja usado o id na composição do mesmo.

_sgce/certificate/views.py_


```
@login_required
def template_preview_render_pdf(request, template_pk):
    template = Template.objects.get(pk=template_pk)
    template_path = 'certificates/template/pdf/preview.html'
    context = {'template': template}

    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="{}-{}.pdf"'.format(template.id, 'Modelo Teste')

```

**Comment by vinigracindo** [comment]
Parece-me que o erro acontece apenas no heroku. No ambiente de teste e no meu ambiente de produção este problema não ocorrer. Deve ser algumas configuração de linguagem do SO no heroku. De qualquer forma vou alterar para id o preview.

Obrigado pessoal pela contribuição.
