### ISSUE TITLE
Criando um Ambiente Virtual

### ISSUE THREAD

**Issue by ronalddmarks** [vinigracindo/sgce#14]
No README.md pede para acessar o diretório "cd /var/www/html/" criar um diretório com nome sgce "mkdir sgce" e baixar o SGCE nesse diretório. 

Quando Inicia o servidor gunicorn funciona perfeitamente na porta 8000.

Quando e feito a configuração do Nginx para o Projeto na configuração do location /static/ ele não consegue encontrar os arquivos do diretório static deixando de mostrar, folhas de estilos e imagens. mesmo dando permissão de leitura e escrita nos diretórios.

 location /static/ {
                root /var/www/html/sgce/sgce;
        }
        location /media/ {
                root /var/www/html/sgce/sgce;
        }

Consegui contornar o erro instalando o projeto no diretório "/var/opt/sgce".

        location /static/ {
                alias /var/opt/sgce/static/;
        }
        location /media/ {
                root /var/opt/sgce;
        }

**Comment by vinigracindo** [comment]
@ronalddmarks Verdade. Eu vou atualizar este tutorial de deploy. Hoje em dia tenho evitado utilizar a pasta /var/www/ por conta das permissões sudo. Eu tenho instalado na /home/ do usuário. Vou atualizar em breve com o mesmo tutorial utilizado pela digital ocean https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04-pt

Eu estou trabalhando também em um arquivo de configuração para subir pelo docker.
