### ISSUE TITLE
Editor de texto não carrega

### ISSUE THREAD

**Issue by aaloise** [vinigracindo/sgce#5]
![image](https://user-images.githubusercontent.com/1064972/59718101-69cc9980-91e7-11e9-9f65-b4441f391757.png)

Quando tento preencher o texto da frente de um modelo, percebi que o editor de texto não é carregado. É um bug ou faltou fazer algo na instalação?

**Comment by vinigracindo** [comment]
Olá aaloise,

O editor de texto é pertence ao módulo django-tinymce. Todos os componentes do requirements.txt foram instalados? Se sim, no console que você está rodando o "python manage.py runserver" apresentou algum erro relacionado ao tinymce? Veja se algum javascript ou CSS não foi carregado. Geralmente aparece o número 404 ao lado no arquivo no console.

**Comment by aaloise** [comment]
Olá @vinigracindo. Todos os componentes do requirements.txt foram instalados sim. No console não apareceu nenhum erro relacionado ao tinymce. Todos os js e css foram carregados. Mas quando habilito a opção "Inspecionar" do Chrome, vejo três erros.

```
select2.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at select2.min.js:1
    at select2.min.js:1
pt-BR.js:3 Uncaught ReferenceError: jQuery is not defined
    at pt-BR.js:3
    at pt-BR.js:3
django_select2.js:14 Uncaught TypeError: $element.select2 is not a function
    at init (django_select2.js:14)
```

**Comment by vinigracindo** [comment]
Eu atualizei algumas dependências nas últimas atualizações. O problema aconteceu comigo também quando clonei o repositório e rodei o projeto. Vi que o problema está no jquery. Vou atualizar os scripts e restaurar o tinymce. O projeto original do django-tinymce não suporta python superior a 3.5, mas o estranho é que no meu ambiente de produção eu já utilizo o python 3.7 e funciona. Eu vou verificar com calma e logo mais efetuarei um commit solucionando o problema. Vou tentar utilizar o django tinymce 2.9.0 uma versão ainda em desenvolvimento mas que já trás suporte ao python 3.6+ e django 2.0+.

**Comment by vinigracindo** [comment]
Resolvido.

**Comment by aaloise** [comment]
@vinigracindo passando apenas para avisar que agora funciona.
