### ISSUE TITLE
Notificações de participantes

### ISSUE THREAD

**Issue by aaloise** [vinigracindo/sgce#6]
Seria interessante adotar a notificação de participantes, de forma parecida com a que o sistema da Unipampa faz, para que os participantes recebam em seu e-mail avisos relacionados aos seus certificados.

**Comment by vinigracindo** [comment]
É uma feature que será adicionada nas próximas versões. O SGCE sofrerá algumas alterações e não manterá mais compatibilidade com o SGCE da Unipampa. Será adicionado as seguintes features que o SGCE da Unipampa já tem:
1 - Notificação dos Participantes
2 - Integração com Ldap/AD.

Além dessas features, as seguintes serão adicionadas/atualizadas:
1 - Gerenciamento de Eventos (Funcionalidade opcional. Fica a cargo do usuário escolher gerenciar e criar certificados ou apenas criar certificados).
---> Gerenciar Inscrições.
---> Gerenciar Papéis (Administrador do Evento, Secretário do Evento, Etc).
---> Gerenciar site do Evento

2 - Reformulação do "gerar certificados".
---> Alterações no handsontable para melhorar a experiência do usuário.

3 - Reformulação do "Avaliar certificados".

Outra coisa é deixar a cargo de quem realiza o deploy escolher no arquivo de configuração o CPF ou E-mail como chave para o participante. 

Todas essas features estão sendo discutidas. Estamos discutindo a melhor forma para os usuários.

**Comment by aaloise** [comment]
Obrigado pela explicação! Se eu puder fazer uma sugestão, seria usar Docker. Senti um pouco de dificuldade em fazer o sistema funcionar, mesmo seguindo o passo-a-passo do Readme.

**Comment by vinigracindo** [comment]
Vou fechar a thread, pois o SGCE será atualizado para uma nova versão.
